Feat/cron added to run suite bh20 4700
sqrtCarlos/mx-beerhouse-ghost-inspector-webhooks pull request #4
Opened 2022-07-07 16:23 UTC by sqrtCarlos

Version 0.1 of the cron job to run the tests suite of ghost inspector.

2022-07-08 15:38 UTC, davidenriquez-zxv requested changes
2 changes

2022-07-08 15:38 UTC, davidenriquez-zxv commented on src/createDeleteSubsScenario.js
> +        console.log('Done!');
remove logs

2022-07-08 15:38 UTC, davidenriquez-zxv commented on src/createDeleteSubsScenario.js
> +        console.log(error);
you should receive a message in slack or somewhere if there is any error

2022-07-08 15:48 UTC, sqrtCarlos commented on src/createDeleteSubsScenario.js
> +        console.log('Done!');
These logs will be removed in the next commits.

2022-07-14 16:38 UTC, davidenriquez-zxv commented on src/utils/slack.utils.js
> +    channels = String(process.env.SLACK_CHANNELS).trim();
why you dont use const to declare the variable?

2022-07-14 19:10 UTC, merged